[package]
name = "sma_q3"
version.workspace = true
authors = [
    "Tock Project Developers <tock-dev@googlegroups.com>",
    "Dorota <gihu.dcz@porcupinefactory.org>"
]
build = "build.rs"
edition.workspace = true

[dependencies]
components = { path = "../components" }
cortexm4 = { path = "../../arch/cortex-m4" }
enum_primitive = { path = "../../libraries/enum_primitive" }
kernel = { path = "../../kernel" }
nrf52840 = { path = "../../chips/nrf52840" }
nrf52_components = { path = "../nordic/nrf52_components" }

core-capsules = { path = "../../capsules/core" }
extra-capsules = { path = "../../capsules/extra" }
