[package]
name = "redboard_artemis_nano"
version.workspace = true
authors.workspace = true
edition.workspace = true
build = "build.rs"

[dependencies]
components = { path = "../../components" }
cortexm4 = { path = "../../../arch/cortex-m4" }
kernel = { path = "../../../kernel" }
apollo3 = { path = "../../../chips/apollo3" }

core-capsules = { path = "../../../capsules/core" }
extra-capsules = { path = "../../../capsules/extra" }