[package]
name = "redboard_redv"
version.workspace = true
authors.workspace = true
build = "build.rs"
edition = "2018"

[dependencies]
components = { path = "../components" }
rv32i = { path = "../../arch/rv32i" }
kernel = { path = "../../kernel" }
e310_g002 = { path = "../../chips/e310_g002" }
sifive = { path = "../../chips/sifive" }

core-capsules = { path = "../../capsules/core" }
extra-capsules = { path = "../../capsules/extra" }
