[package]
name = "litex_arty"
version.workspace = true
authors.workspace = true
build = "build.rs"
edition.workspace = true

[dependencies]
components = { path = "../../components" }
rv32i = { path = "../../../arch/rv32i" }
kernel = { path = "../../../kernel" }
litex_vexriscv = { path = "../../../chips/litex_vexriscv" }

core-capsules = { path = "../../../capsules/core" }
extra-capsules = { path = "../../../capsules/extra" }
