[package]
name = "qemu_rv32_virt"
version.workspace = true
authors.workspace = true
build = "build.rs"
edition = "2018"

[dependencies]
components = { path = "../components" }
sifive = { path = "../../chips/sifive" }
rv32i = { path = "../../arch/rv32i" }
kernel = { path = "../../kernel" }
qemu_rv32_virt_chip = { path = "../../chips/qemu_rv32_virt_chip" }

core-capsules = { path = "../../capsules/core" }
extra-capsules = { path = "../../capsules/extra" }
